'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

/*converted this into a client component as we 
we cannot have session provider in server component -> Learn More About This*/ 

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" h-screen">
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
